### PR TITLE
Feature date picture form

### PR DESCRIPTION
**Pull request by bwbohl**
Adds a parameter $picture-form to date:printDate and passes it to the $get-picture-string call. The idea is to enable a situation dependant picture-string, e.g.

```xquery
switch($picture-form)
   case('long') return '[D1o] [MNn] [Y]'
   case('short') return '[D1o][M1o][Y]'
   default return '[D1o][M1o][Y]'
```

### CODE REVIEW

**Comment by peterstadler** [comment]
Your PR does not incorporate the latest changes, see https://github.com/Edirom/WeGA-WebApp-lib/commit/9171dda5f926b73c05971f0027342219a73f159b 
Could you try to update your fork first and then issue a PR :)

**Comment by peterstadler** [comment]
… and btw, wouldn't it be already possible to do the switch case on the callback function itself, like
```xquery
switch($picture-form)
   case('long') return $myLongCallback
   case('short') return $myShortCallback
   default return $myLongCallback
```

**Comment by peterstadler** [comment]
even more elegant would be to use "Partial Function Applications", see https://exist-db.org/exist/apps/wiki/blogs/eXist/HoF

```xquery
declare function my:callback($picture-form, $lang) { (: … do some stuff depending on $picture-form :) };
let $get-picture-string := my:callback($shortOrLong, ?)
return
  date:printDate($date, $lang, $get-language-string, $get-picture-string)
```

NB: The example is wrong for `$get-picture-string` now takes three parameters!

**Comment by bwbohl** [comment]
> our PR does not incorporate the latest changes, see [9171dda](https://github.com/Edirom/WeGA-WebApp-lib/commit/9171dda5f926b73c05971f0027342219a73f159b)
> Could you try to update your fork first and then issue a PR :)

I did, but obviously I undid one of the  incorporated changes

> … and btw, wouldn't it be already possible to do the switch case on the callback function itself, like
> 
> ```xq
> switch($picture-form)
>    case('long') return $myLongCallback
>    case('short') return $myShortCallback
>    default return $myLongCallback
> ```

And how would the $picture-form be passed to the picture-string callback function when calling date:printDate?
Of course I could implement a bazga:printDate function switching the picture form; at the moment I have the short and long picture-forms in the a config:default-date-picture-string variable function switching between languages and forms.
Maybe I'm missing something…

**Comment by peterstadler** [comment]
> And how would the $picture-form be passed to the picture-string callback function when calling date:printDate?

Here's a complete script that should work within eXist:
```xquery
xquery version "3.1";

import module namespace date="http://xquery.weber-gesamtausgabe.de/modules/date" at "https://raw.githubusercontent.com/Edirom/WeGA-WebApp-lib/develop/xquery/date.xqm";

declare function local:callback($picture-form as xs:string, $lang as xs:string) { 
    switch($lang)
        case 'de' return
            switch($picture-form)
                case('long') return '[D1o] [MNn] [Y]'
                case('short') return '[D1o][M1o][Y]'
                default return '[D1o][M1o][Y]'
        (: do other stuff with other languages :)
        default return error()
};

let $picture-form := 'short'
let $date := <date when="1817-01-01"/>
let $lang := 'de'
let $get-picture-string := local:callback($picture-form, ?)
let $get-language-string := function($term as xs:string, $replacements as xs:string*, $lang as xs:string) { '' }

return
  date:printDate($date, $lang, $get-language-string, $get-picture-string)
```

(It's not working with e.g. Saxon because of the functx import statement in the date module)

**Comment by bwbohl** [comment]
many thanks, this is fantastic!

**Pull request closed without merging**
